- name: Create Volume
  hosts: localhost
  vars_files:
    - storage.json
  vars:
    - myauthstring: "{{storage_username}}:{{storage_password}}"
    - volume_label: "{{my_volume_label}}"
    - volume_capacity_in_gb: "{{my_volume_size_in_gb}}"
  tasks:
    - include: login.yaml

    - include: get_pool_data.yaml
    - name: 'Set My Pool to use'
      set_fact:
        pool_id: "{{ pool_data.json.data.0.poolId }}"
      when: (pool_data.json.data|length >0) and (pool_id is undefined)
    - debug: var=pool_data.json.data.0

    - include: create_volume.yaml

    - include: get_job_status.yaml
    - debug: var=job_status_response.json.affectedResources
    - debug: var=job_status_response
      when: (job_status_response.json.affectedResources is undefined)

    - include: change_ldev_name.yaml

    - include: get_job_status.yaml
    - debug: var=job_status_response
      when: (job_status_response.json.affectedResources is undefined)

    - include: logout.yaml
